### ISSUE TITLE
Can't run artisan in laravel project

### ISSUE THREAD

**Issue by nduydoan** [tarohida/docker-php80-nginx-postgres-composer#1]
When i run cmd
`docker-compose exec php php artisan --version` 

then error below

```
Could not open input file: artisan
```

**Comment by tarohida** [comment]
@nduydoan

Hi! Thank you for creating issue.
This project is not ready to run artisan command.
You have to setup artisan command by yourself in container.

And, this project is not focus on development of Laravel based application.
I recommend you to use [Laravel Sail](https://laravel.com/docs/9.x/sail).
Thank you for reading.
